### ISSUE TITLE
Where is the function named KeyboardEvent to define?

### ISSUE THREAD

**Issue by eric183** [nbarkhina/N64Wasm#17]
Hi
As the title explained, I searched (KeyboardEvent) globally, but still, find nothing. 
Could you just please describe where this function is defined?

**Comment by eric183** [comment]
Thank you so much~

**Comment by nbarkhina** [comment]
All of the keyboard event code is in the c++ code not in the javascript. There probably is a keyboardevent some where in the n64wasm.js glue code but that code is all minified and auto generated by Emscripten so you can't really work with that. You need to use the c++ code.

**Comment by eric183** [comment]
> All of the keyboard event code is in the c++ code not in the javascript. There probably is a keyboardevent some where in the n64wasm.js glue code but that code is all minified and auto generated by Emscripten so you can't really work with that. You need to use the c++ code.

Thank you for answering, I found a relative keyword at RetroArch repo, which is named EmscriptenKeyboardEvent,  maybe it's the answer.

https://github.com/libretro/RetroArch/blob/1ef78d3e3d8e8463790b1fb527510be51a38793a/input/drivers/rwebinput_input.c#L52
