### ISSUE TITLE
SkyEmu iPhone Home Screen bookmarks

### ISSUE THREAD

**Issue by wyldcrd** [nbarkhina/N64Wasm#18]
Skyemu has a cool little feature where if you add a bookmark to the home screen it will remove the search bar.

I got no clue how it works but it would be nice for mobile users

(also dark mode would be nice lol)

**Comment by nbarkhina** [comment]
Thanks for the suggestion, will look into that. Would be cool to see what enhancements are realized by having a progressive web app.

**Comment by wyldcrd** [comment]
One of the enhancements pwas have is offline mode where you can turn off WiFi or cellular and still be able to access the site

**Comment by brismuth** [comment]
I’d love to see this as a PWA with offline mode / app-like look and feel as well. 

Did you end up looking into that @nbarkhina?

**Comment by brismuth** [comment]
@wyldcrd @nbarkhina I created a fork of this repo and added offline gameplay support / installation support. You can see it running here:
https://brismuth.github.io/N64Wasm/

Here is an open pull request to merge the changes in:
https://github.com/nbarkhina/N64Wasm/pull/25
