### ISSUE TITLE
Sram dump to indexdb

### ISSUE THREAD

**Issue by thelamer** [nbarkhina/N64Wasm#3]
Outside of just save states would it be possible to implement "cmd_savefiles" as a callable function to dump sram like you have with Retroarch Emscripten builds?

**Comment by nbarkhina** [comment]
Currently you can already export the sram by turning on advanced mode in settings.js. That will reveal a dropdown during play where you can export the save file:

![response](https://user-images.githubusercontent.com/10982154/147718120-174c3132-e18c-44b5-be84-9b8372eae7aa.PNG)

Saving it to indexedb is possible as well but would require either periodically auto saving it or detecting when there is a change to the save and then doing the save then.

**Comment by thelamer** [comment]
Ahh I see ` neil_export_sra`.
Before I go and fork is it possible to integrate logic to pass a game name to keep SRAM isolated per rom?

**Comment by nbarkhina** [comment]
Yeah the JavaScript code stores the filename as "this.rom_name" in script.js. Though it's not necessary, you could also pass the rom name to the Module if you need. The best place I think you could do it is in script.js in WriteConfigFile(). That is a function that is used to pass a bunch of parameters to the Module on load. The C++ code then reads out the config file in mymain.cpp in "readConfig()". Hope that helps.
