### ISSUE TITLE
Question: Is it also hardcoded that some of the UI elements are blurred?

### ISSUE THREAD

**Issue by BeezBumba** [nbarkhina/N64Wasm#35]
![Screenshot 2024-01-13 121212](https://github.com/nbarkhina/N64Wasm/assets/130922034/43e6a248-b9dc-40cb-a227-d8d3df2df6fd)

In this screenshot of sm64, the press start button is all pixelated via a setting in project 64, however it does not make every texture pixelated like one of the players in mario kart.
![Screenshot 2024-01-13 121441](https://github.com/nbarkhina/N64Wasm/assets/130922034/65ef714c-8dcc-41d4-b234-0c668905b1b6)

is there any sort of setting like that in your code?

**Comment by nbarkhina** [comment]
I'm not aware of what setting that is, what is it called in project 64?

**Comment by kimboslice99** [comment]
Maybe deinterlacing?

**Comment by BeezBumba** [comment]
It's in Texture enhancement tab, and its called Enhancement. It is a drop-down list.

**Comment by BeezBumba** [comment]
If you click "None" that gives you the result of pixelated UI elements.
