### ISSUE TITLE
Different way for saving states.

### ISSUE THREAD

**Issue by BeezBumba** [nbarkhina/N64Wasm#41]
Instead of clicking two save and load state buttons, I could use the game instead. All of the games have a built in save option like OOT or SM64. How would you go by saving that way. I feel like it could help with accidentally clicking save state when loading a game so your progress is not erased.

**Comment by nbarkhina** [comment]
It already does that. Whenever you see the emulator saying "Saving Sram..." it is saving the Save File into the browser. Later if you come back and use the same rom file it will load that Save.

**Comment by BeezBumba** [comment]
Sorry for my part. I am still a little new to coding.

**Comment by BeezBumba** [comment]
Another question, I'm having a hard time finding where the canvas is given the width and height, I would like to have the canvas fill up the screen after you selected the rom. I don't like full screen, mainly on mobile, because when you go in full screen, the keyboard just does not work? It's a problem with safari I'm pretty sure.

**Comment by nbarkhina** [comment]
there's two places, if you are on mobile the it gets it from the window.innerWidth via the setupMobileMode() method in script.js

![image](https://github.com/nbarkhina/N64Wasm/assets/10982154/6dc242b1-2bc8-4b5c-a214-53b3bb292778)

Then it calls resizeCanvas which actually sets the size.

![image](https://github.com/nbarkhina/N64Wasm/assets/10982154/edbb0319-9b98-41f6-977f-7df62d4cb948)

in desktop mode it's based on the zoom setting. basically just set this.canvasSize to whatever you want and then call this.resizeCanvas()

**Comment by BeezBumba** [comment]
Thanks, but when i tried that out it will just fill the whole screen, but since its N64, the screen is more square. is there a way to 
 unlock it so it can stretch based off screen width?

**Comment by nbarkhina** [comment]
that's what it already does it stretches based on screen width. the function resizeCanvas() maintains the correct aspect ratio. what's probably happening is that when the phone is in landscape the square is past the bottom of youre screen.

**Comment by BeezBumba** [comment]
Well how do I unlock aspect ratio. Another person already did it, https://lrusso.github.io/Nintendo64/Nintendo64.htm , but when you try to import the game, it only allows .n64 types. So changing the file extension might work.
