### ISSUE TITLE
Unlock aspect ratio of canvas 

### ISSUE THREAD

**Issue by BeezBumba** [nbarkhina/N64Wasm#42]
How do you unlock the aspect ratio of canvas so I can stretch the canvas based on the windows size I want to fill up the entire screen like https://lrusso.github.io/Nintendo64/Nintendo64.htm . You have to change the file extension of your roms to .n64, it will not accept it otherwise.

**Comment by nbarkhina** [comment]
can you link me to your source code and I can take a look?

**Comment by BeezBumba** [comment]
Sure thing! https://github.com/BeezBumba/N64Emulator/blob/main/index.html

**Comment by nbarkhina** [comment]
here you go -

https://github.com/nbarkhina/N64Emulator-BeezBumba

you can see the changes I made in my commit -

https://github.com/nbarkhina/N64Emulator-BeezBumba/commit/5b5accb9b3cffc0b5eb593fe80e9f97b8c941021
