### ISSUE TITLE
Weird Error when building 

### ISSUE THREAD

**Issue by BeezBumba** [nbarkhina/N64Wasm#50]
sorry to bother you but I just need to know why this is happening. 
![Screenshot 2024-06-04 125846](https://github.com/nbarkhina/N64Wasm/assets/130922034/0be52ee7-2432-4a21-935c-fff68f0eedc1)

**Comment by BeezBumba** [comment]
wanted to update it because VBO was only used for mobile and i want it to be used no matter what.

**Comment by nbarkhina** [comment]
i'll take a look at why the devcontainer doesn't build. in the meantime you could just update script.js to always pass "1" for use VBO. search for this comment and change it to just **configString += "1\r\n";**

![image](https://github.com/nbarkhina/N64Wasm/assets/10982154/7084baa5-a3c2-4ccf-a13e-273542058693)

**Comment by nbarkhina** [comment]
@BeezBumba build issue should now be fixed, I had to make an update to the Dockerfile. You can give it another try and should work now next time you create a new Codespace.

**Comment by BeezBumba** [comment]
Cool!
