### ISSUE TITLE
make reset button?

### ISSUE THREAD

**Issue by TheGhostboi64** [nbarkhina/N64Wasm#9]
is it possible to make a reset button? if so, will you implement it?

**Comment by nbarkhina** [comment]
Yes I it is possible, I will put it on my list of things to add.

**Comment by nbarkhina** [comment]
I added the reset button, you can try it here

https://neilb.net/n64wasm/v2/

**Comment by TheGhostboi64** [comment]
Nice! Can't wait to try it out soon!
